export type AgentPrinciplesComplianceStatus =
  | 'implemented'
  | 'partial'
  | 'missing';

export type AgentPrinciplesCompliancePriority =
  | 'p0'
  | 'p1'
  | 'p2';

export type AgentPrinciplesComplianceItem = {
  section: string;
  status: AgentPrinciplesComplianceStatus;
  priority: AgentPrinciplesCompliancePriority;
  implementedBy: string[];
  gaps: string[];
  nextVerification: string[];
};

export const AGENT_PRINCIPLES_COMPLIANCE: AgentPrinciplesComplianceItem[] = [
  {
    section: 'First Principles And Simplicity',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Task creation and update paths use runtime-task-capture-evaluator to block duplicate and near-duplicate compact titles, generic title-only candidates, generic phase templates, and child titles that merely repeat the parent.',
      'Task title identity adds a conservative action-and-object signature, so generic modifiers cannot hide duplicate task captures or child drafts.',
      'Project decomposition uses runtime-subtask-evaluator before generation and confirmed child creation to avoid duplicate or underspecified subtasks.',
      'Task hierarchy projection treats persisted taskType, taskFacets, parentTaskId, and childTaskIds as authoritative over stale renderer-local attributes.',
      'Legacy title-pattern phase follow-up inference is limited to records without a parent field, and Tasks no longer mutates local hierarchy attributes during list loading.',
      'TasksPage project moves, project decomposition, workspace selection context, completion handoff, Brief projection, RightPanel closeout, and task completion checks use persisted hierarchy fields for active parent/child workflows instead of writing renderer-local hierarchy attributes.',
      'Task attribute storage keeps local hierarchy fields optional, stops writing empty parent/child fields by default, and clears legacy local hierarchy fields after persisted task records provide the hierarchy authority.',
      'TaskHierarchyConsistencyEvaluation, TaskHierarchyRepairPlan, and manual resolution commands separate diagnostics, safe repair, and explicit human confirmation instead of silently guessing structure.',
      'Decisions page surfaces hierarchy manual-review items and safe hierarchy repair actions as explicit user judgments.',
      'No default Artifacts/ folder is required; output folders are created only when useful for the task.',
      'RuntimeTaskCaptureEvaluation blocks generic phase-template task titles even when a faulty flow tries to create them as top-level tasks.',
      'Task hierarchy tests cover explicit no-parent records, explicit top-level phase follow-ups, and renderer stale hierarchy attributes not overriding persisted parent/child fields.',
      'Runtime surface routing has regression coverage that explicit Decision kind, scope, and sourceType are not overridden by title-pattern inference.',
      'RuntimeEntrypointCoverage now requires every retained runtime entrypoint to declare a simplicity_check gate, so future execution, creation, decision, write, resume, and context-transition surfaces cannot register without the smallest-state-change boundary.',
      'MemorySurfaceWriteCoverage requires every retained durable information writer to declare its smallest surface, write policy, and simplicity boundary.',
    ],
    gaps: [
      'Renderer-local hierarchy attributes remain only as legacy missing-field fallback data for old records; future cleanup is limited to deleting compatibility reads when old records no longer need support.',
      'Current retained entrypoints declare the simplicity boundary; future implementation work must keep each concrete surface backed by the smallest applicable evaluator instead of adding broad new workflow steps.',
    ],
    nextVerification: [
      'Keep hierarchy regression tests blocking title-pattern parenting and renderer-local fallback override when structured record fields are present.',
      'Keep runtime-entrypoint coverage tests failing when a future entrypoint omits simplicity_check.',
    ],
  },
  {
    section: 'Runtime Entrypoint Gate Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'RuntimeEntrypointCoverage keeps retained entrypoints explicit for provider-visible execution, provider-visible planning, provider-visible assistance, hidden local execution, task capture, task metadata updates, ordinary task transitions, running/completion transitions, completion-check records, hierarchy maintenance, project decomposition, decision draft, decision creation, decision action, agent tools, durable writes, product configuration, preference memory, method-library writes, capability probes, context transitions, task dynamics, and capability checks.',
      'RuntimeEntrypointCoverage defines kind-level gate baselines so an entrypoint cannot be treated as covered below its class minimum.',
      'RuntimeEntrypointCoverage requires simplicity_check on every retained entrypoint and every kind baseline.',
      'RuntimeEntrypointCoverage maps retained mutable/capability IPC channels back to registered entrypoints while keeping read-only list/filter/detail channels explicitly exempt.',
      'runtime-entrypoint-coverage tests fail when registered entrypoints are missing required gates, fall below their kind baseline, duplicate ownership, or omit simplicity_check.',
      'Renderer entrypoints use shared guards for task capture, task transitions, durable panel actions, project decomposition, task-file writes, task-context switching, automatic clearing, and Decision actions.',
      'TaskService, RunService, CodeAgentRunService, OperatorStartedRunService, AgentToolRegistry, artifact writers, and task repositories keep defensive service and domain boundary gates even when UI callers already checked an action.',
      'Legacy ContextPage and WorkbenchPage are retired, so new entrypoints are expected to land in retained TasksPage, RightPanel, Runs, task dynamics, Decisions, or explicit service boundaries.',
    ],
    gaps: [
      'RuntimeEntrypointCoverage is a regression registry, not dynamic discovery; future entrypoints must be registered and reviewed explicitly.',
      'Future scheduler, connector, provider-visible tool, task-context creation, and Run-side audit surfaces must choose the smallest existing evaluator or design a narrow new evaluator before persistence or execution.',
    ],
    nextVerification: [
      'Keep runtime-entrypoint coverage tests failing when future entrypoints miss their kind baseline or simplicity_check.',
      'During review of any new UI, scheduler, connector, Agent tool, or service write path, require an entrypoint classification and a RuntimeEntrypointCoverage registration before treating it as retained behavior.',
    ],
  },
  {
    section: 'Required Read Order',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'TASKPLANE_AGENT_PRINCIPLES is injected into chat, decomposition, and working context flows.',
      'BriefAttentionBoundary keeps Brief as a capped attention projection over shared priority ordering, not an independent task-management surface.',
      'HomeBriefData exposes BriefAttentionBoundary lanes and reasons beside recommendedActions while retaining the existing Brief layout contract.',
      'BriefFocusProjection keeps Brief task-card inclusion, de-duplication, and parent/child filtering in shared projection data instead of page-local ordering logic.',
      'BriefFocusProjection carries rank, source action id, attention lane, and attention reason into focus-card data so Brief can explain inclusion without a page-local sorter.',
      'BriefExecutor consumes HomeBriefData.briefFocusTasks and briefAttention so generated or fallback briefs preserve the same visible focus list, display-limit, and attention-boundary wording.',
      'BriefProcessTemplateSelector includes HomeBriefData.briefFocusTasks when deciding whether method templates should influence a generated brief.',
      'buildAgentWorkingContext and buildRuntimeContextManifest project task state, sources with freshness metadata, artifacts, files, timeline, and work habits.',
      'RuntimeCapabilitySnapshot can be included in RuntimeContextManifest so model, workspace, flags, and tool scaffold state become explicit context assembly inputs.',
      'RuntimeCapabilitySnapshot preserves full tool scaffold family summaries for capability registry consumers.',
      'RunService and CodeAgentRunService pass RuntimeCapabilitySnapshot into run_start pre-step verification for model/workspace capability checks.',
      'CapabilityRegistry projects runtime capability snapshots into explicit capability entries with status, visibility, access type, approval requirement, and runtime gate.',
      'AiConfigStatus carries CapabilityRegistry so existing model/settings consumers can read the shared capability status without rebuilding local capability semantics.',
      'Sandbox coding capability now depends on sandbox backend probe/readiness in RuntimeCapabilitySnapshot, not just the feature flag.',
      'CapabilityRegistry maps Skills, MCP, and browser/operator scaffold families into hidden reserved/unconfigured rows when product-surface status is absent.',
      'CapabilityRegistry can accept product-surface status for External Access, Skills, MCP, and browser/operator capabilities without making those surfaces model-visible by default.',
      'ConfigurationSafetyReport normalizes AiConfigStatus and CapabilityRegistry into safety-facing configuration states without exposing API key values.',
      'ConfigurationSafetyReport marks provider spend, sandbox, browser, and external-service probes manual-only or explicitly opted in.',
      'AiConfigService attaches ConfigurationSafetyReport to AiConfigStatus so existing settings/model/capability service consumers share one safety projection.',
      'Runtime pre-step verification now checks model execution and workspace verification readiness through CapabilityRegistry.',
      'pre_step verification blocks capability-required execution when RuntimeCapabilitySnapshot is omitted, so future model or workspace entry points cannot silently bypass capability checks.',
      'RunService, CodeAgentRunService, and OperatorStartedRunService pass run_start through TaskMemoryCoverageEvaluation before execution.',
      'Runtime end-to-end scenario tests cover run start blocking without recovery context and next-step state, then passing after Task.md and next-step context exist.',
      'Runtime end-to-end scenario tests cover pending Decisions blocking run start even when Task.md and next-step recovery context are ready.',
      'SourceFreshnessEvaluation classifies source materials as include, caution, or exclude, and RuntimeContextManifest can carry source inclusion decisions and reasons.',
      'SelectedFileRelevanceEvaluation classifies selected files as include, caution, or exclude, and RuntimeContextManifest can carry selected-file relevance reasons.',
      'SourceContext records and creation inputs can carry explicit credibility, duplicate, and sensitive-data signals for source-quality evaluation.',
      'ConnectorSourceIngestionPlan defines the required pre-persistence contract for future connector evidence: connector trace, capturedAt, duplicate, sensitivity, credibility, and quality decision.',
      'buildRuntimeContextAssemblyPolicy evaluates product principles, task state, Task.md, Task Records, selected file, structured signals, and work habits against the required read order.',
      'RuntimeContextAssemblyGate requires read-order assembly for provider-visible task execution and explicitly exempts hidden non-model entries.',
      'RunOrchestrator blocks ordinary model execution when required runtime context inputs are missing.',
      'CodeAgentRunService blocks model-producer execution when required task recovery context is missing and passes selected source-context metadata into RuntimeContextManifest.',
      'RuntimeContextManifest tests cover source-quality metadata propagated through AgentWorkingContext sources, including duplicate, sensitive, and low-credibility signals.',
      'SourceContextMemoryMetadata normalizes source role, credibility, duplicate, and sensitive-data signals before source-context creation or update reaches persistence.',
      'OperatorStartedRunService keeps browser evidence and local QA outside provider-visible context assembly only while providerCall=no and modelExposure=hidden.',
      'TaskMemoryRetrieval provides deterministic execution-memory ranking with include/caution/exclude reasons across task state, Task.md, Task Records, Decisions, sources, artifacts, task files, Work Habits, and process templates.',
      'RuntimeContextManifest consumes TaskMemoryRetrieval and formats its compact read-order summary for provider-visible step context.',
    ],
    gaps: [
      'The shared read-order evaluator is enforced for ordinary model Runs and Code Agent model-producer runs; future provider-visible execution boundaries must use the same gate.',
      'RuntimeContextManifest now consumes TaskMemoryRetrieval; future provider-visible execution boundaries must not rebuild their own task-memory read order.',
      'Source freshness and selected-file relevance reasons are represented in the manifest, ordinary Run working context and Code Agent model-producer runs pass source metadata, but future provider-visible entry points still need to pass full source/file metadata consistently.',
      'Explicit source quality signals exist for retained source contexts and connector ingestion has a shared plan; future real connector services must call it before persistence.',
      'External Access still needs service-backed structured status before it stops being deferred in AiConfigStatus; Skills, MCP, and browser/operator have scaffold fallback but still need richer product-surface status.',
      'ConfigurationSafetyReport is exposed through AiConfigStatus; retained capability/settings pages can consume it when UI work resumes.',
    ],
    nextVerification: [
      'Keep capability registry tests blocking disabled or unconfigured capabilities from becoming model-visible.',
      'Keep configuration safety tests ensuring secret values are not exposed and live probes are manual-only.',
      'Keep AiConfigStatus tests verifying shared registry rows are returned through the existing settings status boundary.',
      'Keep tests that task-bound execution manifests include product principles, task state, Task.md when present, and relevant Task Records.',
      'Keep task-memory retrieval tests covering read-order priority, exclusion reasons, selected-file caution, and query boosting.',
      'Require any future provider-visible execution boundary to use RuntimeContextAssemblyGate and pass full source/file metadata.',
      'Require any future connector ingestion service to use ConnectorSourceIngestionPlan before creating SourceContext records.',
    ],
  },
  {
    section: 'Information Routing Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'runtime-surface-routing classifies Task.md, Task Records, source materials, AI output, artifacts, decisions, work habits, run steps, and discussion-only candidates.',
      'CrossTaskLearningBoundary keeps task-specific corrections in Task Records and routes cross-task habits or reusable SOP-shaped text to confirmation-only proposals.',
      'WorkHabitService consumes CrossTaskLearningBoundary before creating retained Work Habit proposals or SOP-template habit records.',
      'MemorySurfacePolicy gives each runtime surface an explicit memory category, write policy, reuse policy, task-context requirement, and quality-metadata requirement.',
      'MemorySurfaceWriteCoverage registers retained durable information writers and verifies their surfaces, write policies, and required guards.',
      'Artifact classification requires an explicit artifact surface or artifact kind; ordinary task files are not promoted to artifacts by an Artifacts/ path alone.',
      'Memory-surface tests keep AI output distinct from source material, generic source captures distinct from Task Records, and reserved Task.md / Task Records paths out of ordinary file handling.',
      'Source-context routing preserves explicit sourceRole before applying task-record-like title or note heuristics.',
      'Decision, source context, artifact, task file, and work habit creation paths consume shared routing normalization.',
      'Tasks source-context projections consume shared source-context routing instead of maintaining renderer-local Task Record keywords.',
      'TaskRecordWorthinessEvaluation centralizes Task Record-worthy recovery contexts such as handoff, closeout, user correction, option rationale, failure review, context archive, external signal, and durable state change.',
      'RightPanel context-refresh and phase-closeout Task Record writes consume TaskRecordWorthinessEvaluation before persistence.',
      'TasksPage completion handoff and project decomposition self-check Task Records consume TaskRecordWorthinessEvaluation before persistence.',
      'TaskMdUpdateNeedEvaluation centralizes Task.md update needs for recovery fields and important file references.',
      'RightPanel Task.md important-file references consume TaskMdUpdateNeedEvaluation before persistence.',
      'TasksPage direct Task.md saves consume TaskMdUpdateNeedEvaluation before persistence.',
      'TaskRepository update timeline records include changed durable task fields so task dynamics can distinguish summary, next-step, risk, and hierarchy changes.',
      'TasksPage ordinary file creation blocks reserved Task.md and Task Records paths so users cannot bypass the dedicated task-memory evaluators through the generic file entrypoint.',
      'TasksPage manual Task Record creation consumes TaskRecordWorthinessEvaluation and normalizes nested prompts back under Task Records before persistence.',
      'RuntimeRecoveryGuidance centralizes structured Task.md and Task Record recovery recommendations while preserving legacy guidance messages.',
      'RuntimeRecoveryGuidance can derive Task.md recommendations from structured durable task fields, and AgentToolRegistry durable tools pass field metadata instead of hard-coded generic reasons.',
      'AgentToolRegistry durable tool results expose recoveryGuidanceItems and legacy recoveryGuidance from RuntimeRecoveryGuidance without silently mutating Task.md.',
      'AgentToolRegistry persists recoveryGuidanceItems as a separate Run Step so task-memory recommendations remain auditable without silently mutating Task.md or Task Records.',
      'Run output, sandbox patch review, and browser evidence artifacts persist structured Task.md guidance Run Steps without silently mutating Task.md.',
      'TaskMemoryGuidanceState reads structured guidance targets from Run Step input before falling back to guidance text parsing.',
      'TaskMemoryGuidanceState preserves structured reference paths from guidance input for concrete Task.md recovery references.',
      'TaskMemoryWriteProposal projects pending guidance into minimal confirmed-write proposals for Task.md or Task Records without automatically changing task memory.',
      'TaskMemoryWriteProposal preserves existing Task.md content and appends the smallest missing memory note instead of replacing the recovery file.',
      'TaskMemoryWriteProposal writes concrete Important Files entries when pending Task.md guidance carries reference paths.',
      'TaskMemoryWriteApplyPlan converts confirmed proposals into create/update TaskFile inputs and blocks Task.md updates that lack an existing file id.',
      'RunDetailRecord exposes taskMemoryWriteProposals derived from pending TaskMemoryGuidanceState, so runtime consumers can route the missing memory write without recomputing it.',
      'RightPanel routes pending taskMemoryWriteProposals through its existing confirmed task-file proposal card and applies TaskMemoryWriteApplyPlan only after user confirmation.',
      'TaskMemoryGuidanceState distinguishes unresolved task-memory guidance from completed Task.md or Task Record writes.',
      'TaskMemoryGuidanceState tracks Task.md and Task Record guidance per target so one newer recommendation cannot mask another pending memory surface.',
      'TaskRecordWorthiness tests cover should-create and should-not-create cases for handoff, closeout, correction, option rationale, failures, external signals, duplicates, generic notes, and unbound notes.',
      'Memory-surface write coverage tests keep recovery memory behind dedicated evaluators, source/AI output behind explicit source capture, and artifacts behind artifact writers.',
      'Source-context metadata tests keep unknown credibility explicit, detect sensitive content, preserve existing sensitivity flags, and keep generated task records in digest role.',
      'Connector source ingestion tests keep future connector evidence behind trace, capturedAt, duplicate, sensitivity, and credibility planning.',
    ],
    gaps: [
      'TaskMdUpdateNeedEvaluation covers RightPanel important-file references, TasksPage direct Task.md saves, reserved Task.md path protection, AgentToolRegistry durable tool guidance through structured fields, and TaskRepository update timeline changed-field metadata; remaining retained durable writes outside durable tools must pass changed fields and reference metadata consistently.',
      'TaskRecordWorthinessEvaluation is consumed by current retained Task Record writers, including RightPanel context-refresh/phase-closeout, TasksPage manual records, completion handoff, project decomposition self-check, and AgentToolRegistry recovery guidance; future Task Record writers must keep using the same evaluator.',
      'RightPanel can confirm task memory write proposals; TasksPage and any future retained surfaces still need to reuse TaskMemoryWriteApplyPlan instead of rebuilding proposal write inputs.',
      'MemorySurfaceWriteCoverage is an explicit registry, so future durable writers must be added there before they count as covered.',
      'Future connector ingestion services still need to be wired, but the retained source-context boundary now has a shared ingestion plan for connector-specific credibility and duplication signals.',
      'Retained Work Habit proposal and SOP-template writes consume CrossTaskLearningBoundary; future learning writers should keep using that service boundary.',
    ],
    nextVerification: [
      'Keep memory-surface write coverage tests failing when a future writer omits its surface, write policy, guard, or simplicity_check.',
      'Keep information-routing tests in place for task mutation, Task.md update recommendation, and Task Record worthiness when adding new durable write surfaces.',
    ],
  },
  {
    section: 'Task Creation Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Global panel task capture routes through task_capture action evaluation.',
      'TasksPage explicit task creation now passes through the shared task_capture pre-step guard before persistence.',
      'runtime-intake-evaluator classifies user input before task capture as task, Task Record, task file, Decision, Work Habit, or discussion.',
      'runtime-task-capture-evaluator blocks duplicate and near-duplicate open-task captures plus generic title-only candidates before persistence, including conservative action/object duplicates with generic modifiers.',
      'runtime-task-capture-evaluator blocks generic phase-template task titles, generic phase-template child titles, and child titles that only repeat the parent.',
      'TasksPage explicit task creation and RightPanel conversation capture consume the shared task-capture evaluator.',
      'TasksPage explicit task creation forwards the same task summary used by the capture evaluator to the service boundary.',
      'TaskService.create enforces the same duplicate/generic task-capture evaluator before repository persistence.',
      'TaskService.update reuses the same evaluator for title changes and parent moves, preventing duplicate sibling tasks.',
      'TaskService blocks child creation and child moves unless the parent is an open top-level project task.',
      'Project decomposition creates draft subtasks before real child task creation.',
    ],
    gaps: [
      'RightPanel capture uses the shared intake evaluator, TasksPage explicit creation uses the shared task_capture guard, and TaskService.create enforces duplicate/generic candidate checks at the service boundary.',
      'Current retained task creation entry points are scoped: TasksPage explicit capture uses intake/capture guards, RightPanel task capture remains global-only, and project child creation uses the subtask draft evaluator.',
      'Subtask creation has service-level generic child and parent-ownership guards; future child-task creation paths must keep using the same shared confirmation boundaries.',
    ],
    nextVerification: [
      'Route future task creation entry points through RuntimeIntakeEvaluation, TaskCloseoutEvaluation, or a stricter child-task evaluator according to context.',
    ],
  },
  {
    section: 'Project And Subtask Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Project drafts include title, summary, acceptance criteria, dependency, and rationale.',
      'CanonicalDataContract documents canonical task hierarchy fields, legacy fallback boundaries, and repair routes before migration or repair behavior is changed.',
      'CanonicalDataDiagnostics reports missing canonical fields, orphan task references, and missing task-scoped Decision bindings as read-only diagnostics before any repair flow mutates records.',
      'Phase closeout now prefers handoff to existing child tasks instead of generating generic follow-up tasks.',
      'Task closeout evaluation can hand off to an existing successor when no child is available, and new follow-up proposals require evidence and confirmation instead of being created during closeout.',
      'runtime-subtask-evaluator blocks duplicate, near-duplicate, action/object duplicate, generic, parent-overlapping, or underspecified subtask drafts before confirmed child creation.',
      'Project decomposition generation and confirmation both consult runtime-subtask-evaluator so existing children block another decomposition round before new drafts appear.',
      'Project decomposition generation detects existing children from the full task list, including children linked only by parentTaskId.',
      'TaskService keeps child parentTaskId and parent childTaskIds synchronized when child tasks are created, moved, or changed from the parent child list.',
      'TaskService blocks child creation, child moves, and parent child-list writes unless the parent is an open top-level project task.',
      'TaskService safe hierarchy repairs and explicit manual hierarchy resolutions pass parent/child structure writes through task_mutation guards.',
      'runtime-verification has an initial project mode for child completion, blocker/waiting counts, parent criteria, pending decisions, and risk confirmation.',
      'decision-effect-evaluator summarizes pending, approved, deferred, and cancelled decisions for project verification.',
      'Task completion modal uses project verification for project parent completion checks.',
      'Project detail surfaces display project verification next to the child task structure.',
      'TaskService completion transitions run project verification for project parents before writing completed state.',
    ],
    gaps: [
      'Project-level verification now guards project completion transitions; future non-completion project state transitions must consume the same verifier when they affect project readiness.',
      'CanonicalDataDiagnostics covers read-only mechanical checks; future repository and service write paths should consume canonical field authority where write-time validation becomes mechanical.',
      'Subtask draft evaluation exists for project decomposition draft generation and confirmed project child creation, while service-level capture and hierarchy guards cover generic child-title and invalid parent ownership mistakes; future child-task paths must preserve that common confirmation boundary.',
    ],
    nextVerification: [
      'Route remaining project state transitions through project verification.',
      'Route every child-task creation path through a shared confirmation boundary backed by runtime-subtask-evaluator or runtime-task-capture-evaluator.',
    ],
  },
  {
    section: 'Subtask Start Evaluation',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Product principles define a lightweight subtask start evaluation before entering or executing a subtask.',
      'SubtaskStartEvaluation provides a shared runtime object for target task boundary, blockers/dependencies, pending decisions, handoff review, context cleanliness, and context sufficiency.',
      'RuntimeContextAssemblyGate, RuntimeHandoff, RuntimeResumePlan, and runtime verification already provide pieces of task-bound context refresh, handoff, and pre-step checks.',
      'runtime-verification exposes subtask_start mode so subtask start readiness can be evaluated through the same verification surface as execution and closeout checks.',
      'RuntimeResumePlan can carry an optional subtask_start verdict for phase-closeout handoff to a child or successor task before entering the target task.',
      'TasksPage completion handoff reads the next task detail and checks task memory, completion criteria or next step through subtask_start before entering the next child task.',
      'RunService, CodeAgentRunService, and OperatorStartedRunService run subtask_start target-readiness checks before creating task-bound work.',
      'Paused run continuation validates the resume checkpoint first, then rechecks the target task with subtask_start before resuming tools.',
      'Approved checkpoint Decisions recheck target-task readiness with subtask_start before resuming tool, browser, or patch-promotion execution.',
      'TaskService blocks direct transitions into running when target readiness still shows an active blocker, dependency, or waiting state.',
      'Project decomposition and task closeout flows already prefer existing child tasks and handoffs instead of creating generic follow-up tasks.',
    ],
    gaps: [
      'SubtaskStartEvaluation now guards phase-closeout handoff, completion handoff, direct running transitions, approved checkpoint resume, paused run continuation, ordinary Run starts, Code Agent starts, and operator-started runs; future retained task-entry paths must pass parent, handoff, and context signals before starting.',
      'Context cleanliness and context sufficiency are represented in one runtime verdict, but run-start service checks currently use a deliberately minimal target-readiness input to avoid overblocking older tasks.',
    ],
    nextVerification: [
      'Route future explicit task-enter actions through SubtaskStartEvaluation before provider-visible execution.',
    ],
  },
  {
    section: 'Execution Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Runs and run steps record plans, tool calls, tool results, checkpoints, failures, and terminal verification.',
      'Agent tool registry gates risky local command/write tools through checkpoints and Decisions.',
      'DecisionService draft requires an existing task and routes process-template annotations through task_mutation before returning an AI or fallback draft.',
      'DecisionService create normalizes Decision scope and requires task existence before task-scoped Decision persistence.',
      'Runtime action evaluator now covers run start/resume, task mutation, task state transition, context clear, phase closeout, and file proposals.',
      'runtime-verification has first-pass pre_step and post_step modes for execution permission and durable-change recovery notes.',
      'pre_step runtime verification can consume RuntimeCapabilitySnapshot when an execution explicitly requires model execution or workspace verification.',
      'RunService, CodeAgentRunService, and OperatorStartedRunService pass run_start through pre_step verification.',
      'DecisionService approve/defer/cancel actions pass through decision_action pre-step verification at the service boundary.',
      'TaskService transition and transitionIfAllowed pass task_state_transition through pre-step verification at the service boundary.',
      'TaskService completion transitions require task_completion memory coverage before writing completed state.',
      'Task completion memory coverage ignores Run and completion-check evidence older than the latest completion-criteria update.',
      'TaskService completion-check records pass task_mutation before appending durable completion-check timeline evidence.',
      'Runtime end-to-end scenario tests verify completion remains blocked without durable evidence and passes after a recorded completion check.',
      'TaskService task metadata updates are registered separately from task capture, state transitions, hierarchy maintenance, and file/artifact writes.',
      'TaskService waiting transitions require a waiting reason before writing waiting_external state.',
      'TaskService task updates, task-bound source contexts, blockers, completion criteria, dependencies, and process-template bindings pass task_mutation through pre-step verification at the service boundary.',
      'Main IPC task-file and manual-artifact write boundaries pass task_mutation through pre-step verification before repository writes.',
      'RunService, CodeAgentRunService, and OperatorStartedRunService also pass target-task readiness through subtask_start before run creation.',
      'Persisted Run step verification now uses post_step verification.',
      'RunService checks completed Run output artifact writes with post_step durable-change verification before persisting generated output.',
      'Sandbox patch review and browser evidence persisters check artifact writes with post_step durable-change verification before persisting generated evidence artifacts.',
      'runtime-step-effect-evaluator feeds post_step verification with durable-change and recovery-note signals.',
      'RightPanel phase closeout uses pre_step and post_step verification around task-record persistence.',
      'RightPanel task file proposal confirmation uses pre_step and post_step verification around durable file writes.',
      'Tasks and Brief state transitions use shared renderer runtime guards backed by pre_step verification.',
      'Tasks special mutation paths for Task.md sync, risk updates, project moves, and project parent updates use shared mutation guards.',
      'Tasks file actions use durable panel action guards backed by pre_step and post_step verification.',
      'Tasks file content saves, project decomposition writes, and completion criteria creation now use renderer runtime guards before durable persistence.',
      'TaskService completion criteria creation and updates use CompletionCriteriaEvaluation before durable persistence.',
      'TaskService dependency creation and updates use TaskDependencyBoundaryEvaluation before durable persistence.',
      'TaskService blocker creation and updates use BlockerBoundaryEvaluation before durable persistence.',
      'AgentToolRegistry task/source/artifact durable tools use pre_step and post_step runtime verification.',
      'RightPanel internal phase/context record writes use durable panel action guards.',
      'RightPanel task capture, captured-task confirmation, and captured-task abandonment use runtime verification guards.',
      'RightPanel does not expose task capture inside an active task context, and follow-up task proposals remain behind the shared closeout evaluator for future task-context creation entry points.',
      'Known panel runtime timeline event types are constrained through runtime-panel-events and rejected in TaskService when unknown panel.* types are written.',
      'TasksPage file/source/artifact actions and project decomposition confirmation now persist panel.* timeline events for RuntimeEventRecord audit projection.',
      'TasksPage project membership changes and completion handoffs now persist panel.* timeline events with task-to-task context.',
      'TaskService recordTimelineEvent guards panel.* task dynamic writes with task_mutation before persistence.',
      'RuntimeEntrypointCoverage keeps retained execution, planning, assistance, resume, capability-probe, context-transition, task-capture, task-metadata, ordinary task-transition, running/completion transition, completion-check records, project-decomposition, decision-draft, decision-write, decision-action, agent-tool, product-configuration, preference-memory, method-library, and durable-write entrypoints explicit with required runtime gates.',
      'RuntimeEntrypointCoverage defines kind-level gate baselines so future entrypoints cannot register below their class minimum without a failing regression test.',
      'RuntimeEntrypointCoverage includes simplicity_check in every kind-level baseline and retained entrypoint, tying execution expansion back to the first-principles smallest-state-change rule.',
      'RuntimeEntrypointCoverage tests compare retained IPC handlers with registered entrypoint channel claims plus explicit read-only exemptions.',
      'RuntimeEntrypointCoverage is intentionally a regression registry; future runtime entrypoints must be added there and wired to the kind-level baseline rather than relying on dynamic discovery.',
    ],
    gaps: [
      'Current retained execution and durable-write paths are guarded; future scheduled/event execution, new provider-visible tools, or new panel write paths must explicitly pass the smallest matching verification gates.',
      'RuntimeEventRecord projection and replay grouping are consumed in Tasks task dynamics; Run-side and other future retained surfaces must reuse the same projection instead of introducing parallel task-dynamics logic.',
      'Legacy WorkbenchPage remains retired; new runtime behavior must land in TasksPage, RightPanel, Runs, task dynamics, or Decisions instead.',
    ],
    nextVerification: [
      'Require any future execution service or panel durable action to opt into the matching pre_step/post_step verification before persistence, while direct task-bound service writes stay behind task_mutation plus pre_step.',
      'Require any future task-dynamic surface to consume RuntimeEventRecord and groupRuntimeEventsForReplay rather than raw timeline-only data.',
    ],
  },
  {
    section: 'Task.md Rules',
    status: 'partial',
    priority: 'p1',
    implementedBy: [
      'Task.md is classified as task state and Task.md edits sync back to the structured task record.',
      'RightPanel can ensure Task.md exists and reference phase records from task memory.',
      'RightPanel important-file reference writes are gated by TaskMdUpdateNeedEvaluation.',
      'TasksPage direct Task.md saves are gated by TaskMdUpdateNeedEvaluation.',
      'TasksPage generic file creation rejects reserved Task.md paths before persistence.',
      'AgentToolRegistry durable tool results recommend Task.md recovery updates when tool writes affect next step, completion criteria, artifacts, sources, or durable state.',
      'TaskMdUpdateNeedEvaluation can consume structured durable task fields so future write paths do not need to infer Task.md reasons from prompt text.',
      'TaskRepository update timeline records expose structured changed durable fields for direct task updates.',
    ],
    gaps: [
      'Future durable write surfaces must pass structured changed fields and reference metadata into TaskMdUpdateNeedEvaluation instead of relying on text-only heuristics.',
      'Important created/modified files are routed through structured task-memory guidance when produced by durable tools; future write surfaces must preserve the same reference metadata.',
    ],
    nextVerification: [
      'Keep TaskMdUpdateNeed coverage for goal/scope/progress/decision/blocker/next-step/file-reference changes as new write paths are added.',
    ],
  },
  {
    section: 'Task Records Rules',
    status: 'partial',
    priority: 'p1',
    implementedBy: [
      'Context clearing and phase closeout create Task Records only when specific handoff/recovery content exists.',
      'Runtime action evaluator distinguishes task_record surfaces from timeline and ui-only actions.',
      'TaskRecordWorthinessEvaluation provides shared reasons for when a Task Record should or should not be created.',
      'RightPanel context-refresh and phase-closeout Task Record writes are gated by TaskRecordWorthinessEvaluation.',
      'RightPanel phase closeout also checks TaskMemoryCoverageEvaluation after record persistence before refreshing context or handing off.',
      'TasksPage manual Task Record creation is gated by TaskRecordWorthinessEvaluation and always persists under Task Records.',
      'TasksPage completion handoff and project decomposition self-check records are gated by TaskRecordWorthinessEvaluation.',
      'TasksPage generic file creation rejects Task Records paths so Task Record files stay behind TaskRecordWorthinessEvaluation.',
      'Task completion modal checks TaskMemoryCoverageEvaluation before treating completion as clean; insufficient memory becomes a recorded override concern.',
      'AgentToolRegistry source-context writes pass through TaskRecordWorthinessEvaluation before recommending Task Record creation, so ordinary raw sources stay source context and only recovery-worthy external signals become Task Record guidance.',
      'TaskRecordWorthiness tests cover positive and negative creation boundaries.',
    ],
    gaps: [
      'Future retained tool-driven Task Record creation entry points must keep using TaskRecordWorthinessEvaluation instead of creating records from generic summaries.',
    ],
    nextVerification: [
      'Keep Task Record worthiness tests aligned with any new retained tool-driven Task Record entry point.',
    ],
  },
  {
    section: 'Source Materials Protocol',
    status: 'partial',
    priority: 'p1',
    implementedBy: [
      'Source contexts carry kind, role, capturedAt, runId, and batch metadata.',
      'Source creation normalizes missing source roles through shared routing.',
      'SourceFreshnessEvaluation scores archived, selected, current-run, key, stable, recent, stale, and undated sources.',
      'SourceMaterialQualityEvaluation scores traceability, credibility, duplication, and sensitivity before source material is included in runtime context.',
      'RuntimeContextManifest combines source freshness and quality decisions into source-context inclusion metadata.',
      'SourceContext records, creation inputs, Agent working context, and Agent source_context.create can carry explicit credibility, duplicate, and sensitive-data signals.',
      'ConnectorSourceIngestionPlan routes future connector evidence through the same source-quality evaluator before persistence.',
    ],
    gaps: [
      'Source material quality checks are shared and represented in context manifests; future connector services must use ConnectorSourceIngestionPlan to populate explicit credibility, duplicate, and sensitivity signals consistently.',
      'Source inclusion metadata is data-level only; retained UI surfaces do not yet expose full source-quality explanations.',
    ],
    nextVerification: [
      'Pass explicit credibility, duplicate, and sensitivity signals from future connector ingestion paths through ConnectorSourceIngestionPlan into SourceMaterialQualityEvaluation.',
    ],
  },
  {
    section: 'Working Files And Outputs',
    status: 'partial',
    priority: 'p1',
    implementedBy: [
      'No default Artifacts/ folder is required.',
      'Ordinary chat-driven task file writes use proposal flow before writing.',
      'AI output, source material, task record, artifact, and ordinary file labels come from shared classification.',
    ],
    gaps: [
      'Important output references from durable tools, Run output artifacts, sandbox patch review artifacts, and browser evidence artifacts are preserved through structured task-memory guidance; future output surfaces must reuse the same reference propagation path.',
    ],
    nextVerification: [
      'Keep output-reference verification aligned when new artifact-producing surfaces are added.',
    ],
  },
  {
    section: 'Verification Protocol',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'runtime-verification normalizes run, run_step, pre_step, post_step, subtask_start, task_closeout, project, and context_clear checks.',
      'Run verification persistence, completion modal, project completion checks, phase closeout, context clearing, generated artifact writes, panel durable actions, and tool durable writes consume runtime verification.',
      'TaskService project completion transitions consume project verification before persisting completed state.',
    ],
    gaps: [
      'Project-level verification is wired into completion, structure views, and TaskService project completion; future project-level state transitions must consume the same verification before adding new readiness paths.',
      'Pre-step and post-step verification cover current retained execution paths, while direct task-bound durable writes use task_mutation plus pre_step; future execution surfaces must opt in rather than adding direct writes.',
    ],
    nextVerification: [
      'Keep pre_step and post_step runtime verification as the required boundary for future execution services, and use task_mutation plus pre_step as the minimum service boundary for direct task-bound durable writes.',
    ],
  },
  {
    section: 'Task-Level Closeout And Next-Task Evaluation',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'task-closeout evaluator classifies ready_to_complete, needs_user_confirmation, pause_with_handoff, continue_current_task, and handoff_to_existing_child.',
      'Phase closeout writes a Task Record and hands off to an existing child when available.',
      'Context switching refreshes around the target task instead of carrying stale chat by default.',
      'runtime-handoff provides a shared RuntimeHandoff and RuntimeResumePlan for context refresh, task switch, phase closeout, and run resume planning.',
      'RuntimeResumePlan can carry a subtask_start gate when phase closeout hands off to a target task and the caller provides target task context.',
      'Runtime end-to-end scenario tests cover phase closeout to an existing child, pending memory-guidance blocking, and confirmation-gated follow-up task creation.',
      'Runtime end-to-end scenario tests cover blocking task switches until recoverable current-task discussion has been archived.',
      'RightPanel consumes RuntimeHandoff for refresh, manual refresh, leave-context, start-global, task-switch confirmation, and phase-closeout child handoff.',
      'RunService paused-run continuation consumes RuntimeHandoff and RuntimeResumePlan before executing checkpoint resume tools.',
      'runtime-event-record projects timeline events, Runs, Run steps, Task Records, Decisions without timeline coverage, and runtime resume projections into a shared RuntimeEventRecord audit stream for retained task-dynamics surfaces.',
      'runtime-event-record groups projected events into replay-oriented stories for handoff, project structure, execution recovery, Decisions, durable records, source context, and task state.',
      'runtime-event-record formats completion-criteria, dependency, blocker, and source-context payloads into readable task dynamics instead of exposing raw event names or JSON.',
      'RunService.getDetail exposes optional runtimeEvents and runtimeReplayGroups with task-bound timeline and Task Record context on RunDetailRecord for Run-side data consumers.',
      'Tasks task dynamics consumes RuntimeEventRecord projection and replay groups instead of raw task timeline only.',
      'Tasks task dynamics renders replay groups with source labels, time spans, related-task counts, and representative event titles before the flat event timeline.',
      'Tasks task dynamics loads selected Run details and feeds Run steps into RuntimeEventRecord so execution steps remain visible in the same task-bound audit stream.',
      'RightPanel context refresh, context switch confirmation/dismissal, phase closeout, and task file proposal writes persist panel.* timeline events for RuntimeEventRecord audit projection.',
      'TasksPage file/source/artifact actions and project decomposition confirmation persist panel.* timeline events for the same RuntimeEventRecord audit projection.',
      'TasksPage project membership changes and completion handoffs persist panel.* timeline events for task-to-task replay.',
      'runtime-panel-events constrains known panel.* event types before TaskService writes them to timeline.',
      'TaskService recordTimelineEvent guards panel.* task dynamic writes with task_mutation before persistence.',
      'RuntimeEventRecord preserves task-to-task relatedTaskId for completion handoff and accepted context switch events, and replay groups retain relatedTaskIds.',
      'Successor-task handoff beyond child tasks has closeout and replay metadata, while new follow-up task creation remains confirmation-gated.',
    ],
    gaps: [
      'Run checkpoint resume has a shared resume-plan shape and RuntimeEventRecord projection data; future Run-side audit surfaces should reuse the task-dynamics replay layer only if they are explicitly reintroduced.',
      'Follow-up proposal gating exists in the shared closeout evaluator; future task-context creation entry points must use the same boundary before creating follow-up tasks.',
    ],
    nextVerification: [
      'Keep future task-context follow-up creation entry points wired into the shared closeout evaluator.',
    ],
  },
  {
    section: 'Subagent Protocol',
    status: 'partial',
    priority: 'p1',
    implementedBy: [
      'Product principles include the required subagent boundaries.',
      'SubagentHandoffEvaluation verifies inherited principles, task context, narrow scope, allowed action/file scope, confirmation boundaries, and handoff completeness before main-Agent integration.',
    ],
    gaps: [
      'SubagentHandoffEvaluation exists as a shared runtime object, but no retained product entry point exposes subagent delegation yet.',
      'Subagent handoff evaluation is not yet persisted into task memory or RuntimeEventRecord because subagent delegation is not a product action surface yet.',
    ],
    nextVerification: [
      'When subagent delegation becomes a product action, route every subagent result through SubagentHandoffEvaluation before task memory, file writes, or user-facing handoff.',
    ],
  },
  {
    section: 'Context Clearing And New Conversations',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Context clear actions require specific handoff signals before clearing active task discussions.',
      'RightPanel distinguishes refresh, manual refresh, leave task context, and new conversation.',
      'Context clear now combines runtime action evaluation with context-clear runtime verification.',
      'TaskMemoryCoverageEvaluation enforces the Task Memory Spec outcomes for context clearing before chat context can be discarded.',
      'AutoContextClearReadiness turns memory coverage into automatic-clear readiness outcomes without using a hard message-count rule.',
      'AutoContextClearReadiness can consume TaskMemoryGuidanceState so unresolved task-memory guidance blocks clearing until matching memory writes exist.',
      'Runtime end-to-end scenario tests cover pending Decisions blocking task switch and automatic context refresh even after task memory has been archived.',
      'RuntimeHandoff context refresh, leave-context, and global-conversation paths consume AutoContextClearReadiness before clearing task chat.',
      'RuntimeHandoff task-switch checks TaskMemoryCoverageEvaluation before leaving the previous task context, and also blocks unresolved TaskMemoryGuidanceState through AutoContextClearReadiness.',
      'RuntimeHandoff resume_run blocks pending Decisions, blockers, unresolved task-memory guidance, and active short-term reasoning before checkpoint execution can continue.',
      'RightPanel phase closeout consumes TaskMemoryCoverageEvaluation and pending TaskMemoryGuidanceState so handoff signals and task-memory suggestions must be written before chat refresh or next-task handoff.',
      'RuntimeHandoff phase closeout blocks chat clearing when the closeout result still has blocker, dependency, user-confirmation, or follow-up-confirmation work.',
      'Run start pre-step verification consumes pending TaskMemoryGuidanceState so unresolved task-memory writes block new execution.',
      'Paused Run resume consumes pending TaskMemoryGuidanceState before executing checkpoint tools.',
      'Approved Decision checkpoint resume consumes pending TaskMemoryGuidanceState before executing checkpoint tools.',
      'Task completion modal consumes TaskMemoryCoverageEvaluation for completion evidence and memory sufficiency.',
      'TaskService direct transitions into running consume TaskMemoryCoverageEvaluation for task-start memory sufficiency.',
      'RuntimeHandoffPreview represents manual refresh/archive preview as reusable runtime data instead of RightPanel-only text assembly.',
      'RightPanel automatic context mode consumes AutoContextClearReadiness through RuntimeHandoff after refresh triggers, clearing only when recoverable signals were archived and the readiness verdict is safe.',
      'RightPanel task-session transitions now share one reducer for active task, pending switch, input, manual refresh, captured-task confirmation, phase closeout, and task-file proposal state.',
    ],
    gaps: [
      'Selected file is still parent-owned outside the RightPanel session reducer; only promote it into a parent runtime context store if cross-surface context bugs reappear.',
      'New lifecycle boundaries must continue to opt into TaskMemoryCoverageEvaluation instead of bypassing the shared evaluator.',
      'Automatic context clearing is consumed by the retained RightPanel task-chat surface; future background schedulers must reuse the same readiness verdict instead of adding a second clearing rule.',
    ],
    nextVerification: [
      'When UI state work is allowed, keep new task context transitions on the RightPanel reducer or a parent runtime context store backed by RuntimeContextSnapshot and RuntimeHandoff.',
      'Route any new task lifecycle boundary through TaskMemoryCoverageEvaluation without adding extra UI steps.',
      'Keep RightPanel automatic clearing and any future scheduler on AutoContextClearReadiness rather than reintroducing fixed-round clearing.',
    ],
  },
  {
    section: 'Work Habits Boundary',
    status: 'partial',
    priority: 'p2',
    implementedBy: [
      'Work habit proposals use shared routing and confirmation/learning flows instead of writing directly to task files.',
      'RuntimeIntakeEvaluation distinguishes task-specific user corrections, which should become Task Records, from cross-task corrections, which should become Work Habit proposals.',
    ],
    gaps: [
      'RuntimeIntakeEvaluation covers the main task-specific vs cross-task correction boundary, but downstream Work Habit persistence still depends on the confirmation flow.',
    ],
    nextVerification: [
      'Keep user-correction routing tests in place when adding new intake surfaces or Work Habit entry points.',
    ],
  },
  {
    section: 'Decisions, Confirmation, And Self-Check',
    status: 'partial',
    priority: 'p0',
    implementedBy: [
      'Decision creation and drafts use shared routing normalization.',
      'Decision actions pass through runtime action evaluation.',
      'Task-bound Decision actions preflight the target task memory annotation before changing the Decision status.',
      'Checkpointed risky tools create Decisions and resume only after approval.',
      'Decision effect summaries feed project verification for pending, approved, deferred, and cancelled decisions.',
      'Decision effect grouping organizes related decision effects by task first and source when no task is bound.',
      'RuntimeEventRecord replay grouping separates task completion checks into quality_gate groups so closeout verification remains visible as a quality gate.',
      'Decisions page approve/defer/cancel actions use shared decision action guards backed by pre_step and post_step verification.',
      'DecisionJudgmentProjection centralizes decision category, urgency, task signal, options, recommendation, impact, reversibility, and sorting semantics for the Decisions page.',
      'DecisionJudgmentProjection prefers explicit Decision context impact, reversibility, and recommendation reason before generic judgment labels.',
      'DecisionJudgmentProjection standardizes sourceTarget and routeHint for task, run, agent checkpoint, tool, external access, workspace, system, manual, and global decisions.',
      'DecisionJudgmentProjection exposes source kind, source action, and approval boundary labels so the Decisions page can explain what is being judged without inferring from display text.',
      'DecisionService.listJudgments exposes the pending judgment-center projection at the domain boundary.',
      'Decisions page action results summarize approved, deferred, and cancelled effects using decision-effect-evaluator.',
      'DecisionJudgmentProjection attaches grouped pending-decision context by task/source, and the Decisions page shows same-source pending counts and effect detail inside the judgment card.',
      'Decisions page keeps failed action attempts visible with retry feedback and disables duplicate actions while a decision action is pending.',
      'Decisions page expanded cards show judgment object and approval boundary, and search includes source, boundary, recommendation, and context fields.',
    ],
    gaps: [
      'Decisions page now shows grouped pending-decision context; batch approve/defer/cancel remains intentionally deferred until a real multi-decision workflow appears.',
      'Decision sourceTarget routing is data-ready; richer Run/checkpoint navigation remains a future UI concern.',
    ],
    nextVerification: [
      'Keep grouped Decisions read-only unless a concrete multi-decision workflow requires batch actions.',
    ],
  },
];

export function summarizeAgentPrinciplesCompliance(): Record<AgentPrinciplesComplianceStatus, number> {
  return AGENT_PRINCIPLES_COMPLIANCE.reduce<Record<AgentPrinciplesComplianceStatus, number>>((summary, item) => {
    summary[item.status] += 1;
    return summary;
  }, {
    implemented: 0,
    partial: 0,
    missing: 0,
  });
}
