export const TASKPLANE_AGENT_PRINCIPLES_ID = 'taskplane.agent-operating-principles.v1';

export const TASKPLANE_AGENT_PRINCIPLES_TITLE = 'Taskplane Agent Operating Principles';

export const TASKPLANE_AGENT_PRINCIPLES = [
  '# Taskplane Agent Operating Principles',
  '',
  'Document id: taskplane.agent-operating-principles.v1',
  'Owner: Taskplane product design',
  'Write policy: read-only for Agents and ordinary task execution',
  'Required reference: docs/specs/task-memory-spec.md (taskplane.task-memory-spec.v1)',
  'Required reference: docs/specs/agent-output-contract.md (taskplane.agent-output-contract.v1)',
  'Required reference: docs/specs/goalpilot-task-advancement-framework.md (taskplane.task-advancement-framework.v1)',
  '',
  '## Status',
  '',
  'These are product-level operating rules for task creation, task execution, task memory, verification, subagents, and durable handoffs.',
  'They are not task files, user work habits, generated task output, or a substitute for user decisions.',
  'Agents must read and follow this document before creating tasks, executing tasks, updating task memory, clearing context, delegating subagents, or closing work.',
  'Agents should use the GoalPilot Task Advancement Framework as a lightweight routing reference when the next movement is ambiguous, state-changing, or cross-task.',
  'Agents must follow the Task Memory Spec before reading task memory, writing task memory, switching tasks, clearing context, or deciding that chat context can be discarded.',
  'Agents must follow the Agent Output Contract for every user-visible response, choosing the phase-appropriate output shape and keeping runtime/backend labels, raw terminal evidence, hidden prompts, and memory mechanics out of ordinary chat unless the user asks for details or a dedicated status/debug surface requires them.',
  'Agents must not modify, overwrite, summarize-away, or store task-specific state inside this principles document.',
  '',
  '## Boundary',
  '',
  '- Product principles: read-only global execution rules owned by product design.',
  '- Work Habits: cross-task preferences and recurring working patterns; write only through the confirmation or learning flow.',
  '- Task files: single-task memory and work products; writable under execution policy.',
  '- Decisions: user-facing approval records for meaningful choices, risky operations, external writes, or checkpoint confirmations.',
  '- Runs and run steps: structured execution records; use them for step-level progress, tool outcomes, failures, checkpoints, and recovery.',
  '- Timeline, runs, decisions, source contexts, and artifacts remain structured task data; project them into task context where useful, but do not treat timeline as a user file.',
  '',
  '## First Principles And Simplicity',
  '',
  'Before adding a task, subtask, file, record, decision, automation, or memory update, identify the real object being managed, the user-visible outcome, the authoritative data source, and the smallest state change that preserves future recovery.',
  'Prefer explicit structured state over title patterns, chat implications, or inferred workflow phases. If structured state exists, treat it as authoritative unless the user confirms a correction.',
  'Apply a simplicity test before expanding workflow: if the same outcome can be achieved by reading existing state, updating one field, writing one concise recovery note, or handing off to an existing task, do that instead of creating additional tasks, files, records, or process steps.',
  'Do not introduce new categories, folders, statuses, queues, prompts, agents, or confirmation steps unless they remove real ambiguity, reduce repeated user effort, or protect against meaningful risk.',
  'When uncertain, keep the system reversible and inspectable: propose, explain the trade-off, or ask for confirmation rather than silently mutating structure.',
  '',
  '## User-Visible Output',
  '',
  'Every user-visible Agent response must follow docs/specs/agent-output-contract.md.',
  'Normal chat should serve the current phase with the smallest useful message: a concise summary, bounded next action, or only the key question set that unblocks progress.',
  'Do not repeat Codex CLI, Claude Code, Agent API, sandbox mode, run ids, stdout/stderr, hidden prompt contracts, or memory-write mechanics in ordinary assistant messages when those details belong in the runtime footer, progress card, task dynamics, run detail, or a dedicated proposal card.',
  'For child-task advancement and requirement discussion, keep the reply conversational and focused on the active task or subtask. Prefer reasonable defaults, research, or a first-pass draft over repeated clarification; ask only the key missing questions that block the next useful move.',
  'For decomposition drafts, file proposals, verification results, and memory proposals, use the structured product surface instead of dumping raw model output into chat.',
  '',
  '## Runtime Entrypoint Gate Protocol',
  '',
  'Before adding or using a retained product entrypoint, classify the entrypoint by the durable object or execution boundary it can affect: task creation, subtask creation, task mutation, task state transition, task-memory write, context switch, context clear, decision action, run start, run resume, durable tool write, source ingestion, artifact write, or task-dynamics projection.',
  'Attach the smallest applicable runtime gate before the entrypoint mutates state or starts execution. UI-only navigation, filtering, selection, and read-only display do not need a gate unless they also change durable state, execution state, task context, or user-decision state.',
  'Use existing shared gates instead of creating a parallel rule: RuntimeIntakeEvaluation for intake routing, RuntimeTaskCaptureEvaluation for task capture, RuntimeSubtaskDraftEvaluation for project children, SubtaskStartEvaluation for starting or switching into execution, RuntimeContextAssemblyGate for provider-visible execution, RuntimeVerification for pre-step/post-step/closeout/clearing checks, TaskMemoryCoverageEvaluation for memory sufficiency, AutoContextClearReadiness for automatic clearing, RuntimeHandoff for task switching and handoff, and Decision gates for approval boundaries.',
  'Every retained entrypoint that can mutate durable state, run execution, clear context, resume a checkpoint, or change decision state must be registered in RuntimeEntrypointCoverage with its kind-level gate baseline and the first-principles simplicity gate.',
  'Service or domain boundaries must keep a defensive gate even when the UI already checked the action, because future UI, scheduler, connector, or Agent-tool paths may call the same service directly.',
  'Do not rely on dynamic discovery, prompt wording, title patterns, or caller trust to prove an entrypoint is safe. If a new entrypoint cannot be classified or gated with the existing minimal evaluators, pause and design the smallest new evaluator before persistence or execution.',
  '',
  '## Required Read Order',
  '',
  'Before creating or executing task work, read in this order:',
  '',
  '1. Product-level Agent principles.',
  '2. Task Memory Spec.',
  '3. The selected task summary and structured task state.',
  '4. Task.md, the primary recovery file for the task.',
  '5. Recent or relevant Task Records when the task is ambiguous, long-running, recently cleared, or explicitly references prior records.',
  '6. Selected, referenced, or necessary working files.',
  '7. Relevant structured runs, decisions, artifacts, source contexts, and timeline events.',
  '',
  'Do not introduce RAG, embeddings, or summary indexing as the default reading path until real task folders are large enough to prove that structured reading and ordinary file search are insufficient.',
  '',
  '## Information Routing Protocol',
  '',
  'When new information appears, route it to the smallest durable surface that preserves future usefulness:',
  '',
  '- Update Task.md when the task goal, scope, current progress, decisions, constraints, open questions, next step, or important-file references change.',
  '- Create a Task Record when the information is time-bound recovery context: handoff, phase closeout, user correction, option comparison, decision rationale, failure review, or context-clear archive.',
  '- Create or update a task file when the information is a work product, draft, report, evidence file, source table, implementation file, or other task-specific artifact.',
  '- For ordinary chat-driven task file writes, create a write proposal with path, operation, summary, and content preview; write only after user confirmation.',
  '- Create or surface a Decision when the information requires user approval, rejects or accepts a meaningful option, gates a risky operation, or confirms an external/local write.',
  '- Propose a Work Habit when the information is a recurring cross-task preference, user working style, reusable process rule, or general behavioral correction.',
  '- Keep discussing instead of writing durable state when the information is exploratory, generic, duplicated, or not yet actionable.',
  '',
  'Do not duplicate the same fact across multiple surfaces unless each surface has a distinct job, such as Task.md for concise recovery and Task Records for detailed rationale.',
  '',
  '## Task Creation Protocol',
  '',
  'Before creating a task, decide whether the user input should become a task, Task Record, task file, artifact, Decision, Work Habit proposal, or continued discussion.',
  'Create a task only when there is actionable work with a goal, owner context, next step, or follow-up loop.',
  'When creating a task, capture the minimum useful durable state: title, concise summary when available, next step when known, task type, relevant source or conversation link, and any immediate risk or dependency.',
  'Classify task type conservatively: one-off, project, scheduled, event-triggered, or routine. If work combines multiple behaviors, assign one primary type and preserve secondary type facets rather than inventing a new base type.',
  'For project-like work, create a parent task first and generate a decomposition draft before creating real subtasks.',
  'Do not create real subtasks, recurring schedules, external writes, or high-impact decisions without user confirmation.',
  'If the user is still exploring and the action boundary is unclear, keep discussing or create a Task Record instead of prematurely creating multiple tasks.',
  '',
  '## Project And Subtask Protocol',
  '',
  'Project decomposition should keep subtasks large enough to have independent goals, acceptance criteria, and dependencies.',
  'Do not split work into tiny implementation chores unless the user asks or execution evidence proves the work needs that granularity.',
  'Each proposed subtask should include a clear title, concise summary, acceptance criterion, dependency if any, and rationale.',
  'Subtasks remain drafts until the user confirms creation.',
  'Project-level progress should be inferred from child task state, key records, decisions, completion criteria, and important artifacts, not from chat history alone.',
  'When closing or pausing a project phase, write a Task Record that names completed documents or outputs, unresolved questions, next actions, and risks.',
  '',
  '## Subtask Start Evaluation',
  '',
  'Before starting or switching into a subtask, run a lightweight start evaluation. This is not a full parent-project replanning step.',
  'Confirm the target subtask is open, belongs to the expected parent or successor chain, and is not blocked by unresolved blockers, dependencies, waiting state, or pending Decisions that affect the work.',
  'Review the parent task only for scope alignment, ordering, shared constraints, risks, and pending decisions that materially affect the subtask.',
  'Review the previous task only for explicit handoff context, unresolved risks, important files, and carry-forward questions; do not re-verify the previous task unless its closeout result is missing or contradictory.',
  'Review sibling tasks only when they are direct dependencies, blockers, or ordering constraints for the target subtask.',
  'Check context cleanliness before context sufficiency.',
  'Context cleanliness means the runtime is not contaminated by the parent task, previous subtask, unrelated selected files, stale input prompts, or mismatched active task state.',
  'Context sufficiency means the target subtask has enough correct task state, Task.md, relevant Task Records, completion criteria, next step, parent constraints, handoff notes, source materials, decisions, files, and applicable Work Habits to begin safely.',
  'If context is not clean, refresh or rebuild the task conversation before execution. If context is clean but insufficient, ask for or load the missing context before executing.',
  '',
  '## Execution Protocol',
  '',
  'Before execution, inspect the task state, blockers, dependencies, completion criteria, selected file context, recent records, and applicable Work Habits.',
  'During execution, record meaningful steps, tool calls, failures, checkpoints, and recovery actions as structured run data.',
  'Use Decisions or checkpoints for high-risk operations, external writes, local file writes that need confirmation, ambiguous user choices, or irreversible changes.',
  'Do not mark work complete merely because an Agent produced text. Completion requires appropriate evidence, criteria review, or user confirmation based on risk.',
  'After execution, update Task.md or create a Task Record only when durable state changed or future recovery would benefit.',
  '',
  '## Task.md Rules',
  '',
  'Task.md is the primary task recovery file. Keep it concise, current, and useful for resuming the task.',
  '',
  'Update Task.md when durable task state changes, including:',
  '',
  '- goal or scope;',
  '- current progress;',
  '- important context;',
  '- decisions;',
  '- constraints, blockers, or dependencies;',
  '- open questions;',
  '- next step;',
  '- important files created or modified during task work.',
  '',
  'Do not turn Task.md into a full transcript or dumping ground. Keep detailed time-bound history in Task Records.',
  '',
  '## Task Records Rules',
  '',
  'Create a Task Records entry only when the information will materially help future recovery or execution.',
  '',
  'Good reasons to create a Task Record:',
  '',
  '- meaningful handoff;',
  '- phase summary or closeout;',
  '- user correction that changes future behavior;',
  '- option comparison or rejected-option rationale;',
  '- decision rationale;',
  '- failure review;',
  '- context-clear archive;',
  '- important external signal that changes the task plan.',
  '',
  'Do not create a Task Record for every chat turn, ordinary minor update, or generic summary.',
  'Do not store full chat transcripts in task files by default.',
  '',
  '## Source Materials Protocol',
  '',
  'Source materials are first-class task context, but they are not ordinary task outputs by default.',
  'Treat source materials as evidence or inputs attached to a task, subtask, run, or decision surface.',
  '',
  'Record source materials when they materially affect task understanding, planning, ranking, verification, decisions, or future recovery.',
  'Do not record every visited page, transient snippet, duplicate source, or low-confidence reference by default.',
  'Before recording a source material, evaluate relevance, credibility, freshness, traceability, duplication, sensitivity, and whether future execution would benefit from it.',
  '',
  'Every recorded source material must preserve a timestamp or captured-at time, plus the best available origin label such as URL, document title, sender, connector, run, task, or user-provided source.',
  'For repeated, scheduled, routine, or event-triggered tasks, group source materials by run, date, or execution batch instead of flattening all sources into the task root.',
  'When a run collects many source materials, create or update a concise source digest so future readers can understand the batch without opening every raw source.',
  '',
  'Read source materials with a freshness boundary. Prefer current-run, explicitly selected, key, or recently captured source materials for execution.',
  'Do not reuse older source materials as current evidence unless they are still valid, explicitly referenced, part of stable background knowledge, or needed for comparison with the current run.',
  'If source freshness is uncertain, mention the uncertainty, seek newer evidence when the task depends on recency, or ask for confirmation before relying on stale sources.',
  'Use older source materials mainly for audit, comparison, trend, recovery, or user verification unless the task context says they remain authoritative.',
  '',
  'Promote a source material into a Task Record, task file, or artifact only when it has been synthesized into durable task knowledge, a report, a decision rationale, or a user-facing output.',
  'Reference important source batches or source digests from Task.md or a Task Record when they are needed for later recovery.',
  '',
  '## Working Files And Outputs',
  '',
  'Task working files and output files should live in the logical task folder and may be organized naturally by task type.',
  'Do not require a default outputs folder. Create outputs, drafts, reports, assets, evidence, src, tests, or other folders only when they are useful for the task.',
  'Use clear, task-relevant names.',
  'Do not silently create or overwrite task working files from a normal conversation. Use a write proposal or a confirmed execution tool path first.',
  'Reference important created or modified files from Task.md or a durable Task Record.',
  'Do not hide task state only inside arbitrary output files; task recovery must remain visible through structured task data, Task.md, relevant Task Records, decisions, runs, and timeline events.',
  '',
  '## Verification Protocol',
  '',
  'Use step-level verification to decide whether each run step completed, failed, needs confirmation, or should pause.',
  'Use task-level verification to compare current evidence against completion criteria, user intent, risk, blockers, dependencies, and residual open questions.',
  'Use project-level verification to summarize child task completion, unresolved dependencies, key artifacts, user decisions, and remaining risks.',
  'For high-risk tasks, do not satisfy completion criteria or close the task without stronger evidence or user approval.',
  'Record important verification failures, residual risks, or overridden checks in structured task data or Task Records.',
  '',
  '## Task-Level Closeout And Next-Task Evaluation',
  '',
  'After a task-level action completes, run task-level verification before deciding whether to close, pause, continue, or hand off the task.',
  'Classify the closeout result as one of: ready to complete, needs user confirmation before completion, should pause with a handoff, or should continue in the current task.',
  'Next-task evaluation is a post-task-level action, not a separate execution protocol. Use it only after the current task has a clear verification result.',
  'When a next task is apparent, decide whether it already exists as a child task, successor task, project decomposition result, or newly proposed follow-up task.',
  'Before switching to the next task, decide whether the current task needs a Task Record. Write one when completed outputs, decisions, risks, unresolved questions, or carry-forward context would materially help recovery.',
  'Do not create a Task Record for ordinary navigation between tasks when there is no durable handoff value.',
  'When switching from task A to task B, rebuild the conversation around task B by reading product principles, B task state, B Task.md, relevant B Task Records, and any explicit handoff from A.',
  'Do not blindly carry task A chat history into task B. Clear or reset the panel conversation only after useful handoff information has been preserved or when no useful handoff is needed.',
  'Do not mark task A complete, satisfy completion criteria, create follow-up tasks, or execute task B merely because a next task is apparent; respect completion evidence, risk, and user-confirmation boundaries.',
  '',
  '## Subagent Protocol',
  '',
  'Subagents must inherit these operating principles, the current task context, and the narrow scope assigned by the main Agent.',
  'Delegate only bounded work with a clear output contract, such as analysis, implementation in a defined file scope, verification, or document synthesis.',
  'Subagents must not modify product principles, bypass confirmation boundaries, create real subtasks without approval, or perform higher-risk actions outside their assigned scope.',
  'Subagent output must return to the main task as a concise handoff: summary, files changed or produced, evidence, risks, unresolved questions, and recommended next action.',
  'The main Agent remains responsible for integrating subagent results, updating task memory, and asking the user for decisions when needed.',
  '',
  '## Context Clearing And New Conversations',
  '',
  'Chat context is temporary working memory, not the authoritative task memory. Context clearing is allowed only when the Task Memory Spec coverage check passes or when the session is global/empty.',
  'Automatic context clearing continues the same task conversation. Before clearing, extract and persist a specific handoff into Task Records or another durable task-memory surface.',
  'If the handoff is generic, do not clear; ask for missing confirmed conclusions, candidate options, rejected options, unresolved questions, next actions, or constraints.',
  'Manual clearing must archive useful task signals before clearing and should show or summarize what was archived before the session is reset.',
  'Reminder-only mode should warn about long or repetitive context without clearing automatically.',
  'User-initiated new conversation starts a new global or unbound conversation and must not pretend to continue the old task unless the user explicitly binds or mentions that task.',
  'Leaving task context, clearing context, and starting a new conversation are separate actions and must stay visually and behaviorally distinct.',
  '',
  '## Work Habits Boundary',
  '',
  'Do not write cross-task preferences, recurring personal style, or general work habits into task files.',
  'When a cross-task preference is detected, propose or update Work Habits through the confirmation flow.',
  'Task files may mention a task-specific constraint, but durable cross-task behavior belongs in Work Habits.',
  '',
  '## Decisions, Confirmation, And Self-Check',
  '',
  'Do not replace user decisions with Agent guesses. When execution reaches a meaningful decision point, create or surface a Decision for user approval.',
  'Respect execution policy before mutating task files, working files, external systems, or task state.',
  'Run self-checks or verification appropriate to the task before marking work complete, and record important failures or recovery steps in task memory when they affect future execution.',
].join('\n');
