export const TASKPLANE_TASK_ADVANCEMENT_FRAMEWORK_ID = 'taskplane.task-advancement-framework.v1';

export const TASKPLANE_TASK_ADVANCEMENT_FRAMEWORK_TITLE = 'GoalPilot Task Advancement Framework';

export const TASKPLANE_TASK_ADVANCEMENT_FRAMEWORK = [
  '# GoalPilot Task Advancement Framework',
  '',
  'Document id: taskplane.task-advancement-framework.v1',
  'Owner: Taskplane product design',
  'Layer: operating-principle / always-loaded task router',
  'Load: always in Taskplane-controlled Agent runtime context',
  'Scope: global task advancement',
  'Authority: required routing reference; detailed phase rules are loaded on demand',
  'Line budget: keep under 200 lines',
  '',
  '## Purpose',
  '',
  'GoalPilot is the short, always-loaded task navigation layer for Taskplane and the operating reference for the Pilot coordination role. It is the single always-loaded product rule for task advancement.',
  '',
  'It decides how work moves from fuzzy intent to shaped, executable, verified, and recoverable task state. It does not contain detailed execution, memory, output, source, or tool rules. Instead, it routes each movement to the smallest needed runtime, rule document, skill, hook, or review path.',
  '',
  'Use it silently. Do not show GoalPilot as a checklist unless the user asks why a movement was chosen.',
  '',
  '## Core Question',
  '',
  'What is the smallest movement that makes this task clearer, more executable, more verified, or more recoverable without creating unnecessary structure?',
  '',
  'Prefer movement over interrogation. Ask only when missing information blocks the next useful action, changes a key risk, or materially changes the deliverable boundary. If the user has given enough signal, state a reasonable default and move forward through research, shaping, drafting, execution, or verification.',
  '',
  'For product, website, documentation, tutorial, or planning tasks, theme, target audience, and content shape are usually enough to advance. Do not keep asking secondary preferences such as private vs public, directory vs learning path, or display style when they can be adjustable defaults in a first draft.',
  '',
  '## Rule Hierarchy',
  '',
  'Keep authority and load order simple:',
  '',
  '- `AGENTS.md` / `CLAUDE.md` are thin native CLI adapters. They point here and should not duplicate product rules.',
  '- GoalPilot is the only always-loaded total rule. It chooses movement and indexes the smallest needed follow-up rule.',
  '- Pilot Coordinator is a role contract for applying GoalPilot plus priority, message, backend, and executor decisions. Load it when Pilot behavior itself matters; do not treat it as a second total rule.',
  '- Priority Attention Routing is a phase-loaded ranking skill shared by Brief and Pilot when tasks compete.',
  '- Execution, output, memory, context transition, source/evidence, writeback, and native runtime rules are phase-loaded skills or architecture specs.',
  '- Hooks and gates are deterministic code constraints. If something must always happen, implement it there instead of relying on model memory.',
  '',
  '## Goal And Pilot Loop',
  '',
  'Goal: understand the work.',
  '',
  '- What is the real goal and owner task: parent, child, successor, or new task?',
  '- Is the boundary clear enough to act?',
  '- What would count as success or acceptable progress?',
  '- Which uncertainty matters: goal, scope, evidence, execution, risk, ownership, blocker, dependency, source, file, or decision?',
  '- Can source review, web research, files, task memory, or runtime tools answer the uncertainty better than asking the user?',
  '- Is the current context clean, or contaminated by another task, stale prompt, unrelated selected file, or previous conversation?',
  '',
  'Pilot: choose the movement.',
  '',
  '- Clarify, research, shape, decompose, select next task, execute, verify, persist, hand off, or pause?',
  '- What is the smallest useful next movement?',
  '- If multiple tasks compete, should Priority Attention Routing choose the focus first?',
  '- Which on-demand rule, skill, runtime, or hook applies?',
  '- Does durable state change require confirmation?',
  '- After this movement, stay on this task, enter a child, return to parent, switch to successor, or stop?',
  '',
  '## Context Readiness',
  '',
  'Before asking or executing, judge whether the context is clean and sufficient.',
  '',
  'Context is sufficient when the goal, owner task, next movement, risk or permission boundary, and recovery source are clear enough for a reversible next step. Missing details are not blockers when they are adjustable defaults or can be learned from files, source review, web research, task memory, runtime tools, or a first-pass draft.',
  '',
  'Self-research before asking when external facts, product examples, official docs, repository state, prior records, or source evidence can answer the gap. Ask the user only when the answer changes the goal, acceptance boundary, irreversible cost, security/legal/credential boundary, external side effect, or a preference only the user can know.',
  '',
  'When context is enough, move. A brief "context is sufficient; starting" status is useful before visible execution, but should not become another planning turn.',
  '',
  '## Situation Map',
  '',
  '| Situation | Default movement | Load next |',
  '| --- | --- | --- |',
  '| Fuzzy intent | Clarify or Shape | Intake / task creation rules if becoming durable. |',
  '| Existing task missing goal, scope, criteria, or next step | Shape | Output contract if responding; memory spec if persisting. |',
  '| Product, website, document, or tutorial with theme, audience, content shape | Research or Shape | Source rules, output contract, or execution rules as needed. |',
  '| Project too broad for one run | Decompose | Decomposition flow; user confirmation before child creation. |',
  '| Project with existing children | Select next task or Verify | Subtask start evaluation; handoff/memory rules if switching. |',
  '| Multiple active tasks compete | Rank and focus | Priority Attention Routing; then selected-task rules. |',
  '| Child task active | Shape or Execute | Child-task scoped rules; do not re-plan parent unless boundary is wrong. |',
  '| Research-dependent task | Research | Source rules and selected runtime/tool capabilities. |',
  '| Executable task | Execute | Agent operating principles and runtime/tool rules. |',
  '| Long-running executable task with clear stop condition | Execute through persistent goal capability when available | Native runtime orchestration, run goal contract, verification gates. |',
  '| Blocked, waiting, risky, or decision-bound | Pause or Decision | Decision/checkpoint hooks. |',
  '| Work produced | Verify | Verification/review rules. |',
  '| Stable pause, closeout, or task switch | Persist or Handoff | Task memory spec and context transition policy. |',
  '',
  'This map is a starting point, not a script.',
  '',
  '## On-Demand References',
  '',
  'GoalPilot chooses when these documents or flows matter:',
  '',
  '- Agent Operating Principles: load for concrete execution, runtime runs, subagents, tool use, state mutation, and completion claims.',
  '- Agent Output Contract: load when rendering chat, progress cards, drafts, proposals, run summaries, verification results, or user-facing files.',
  '- Task Memory Spec: load when reading/writing task memory, switching tasks, clearing context, closing a phase, or deciding if recovery is sufficient.',
  '- Context Transition Policy: load when compacting, resetting, clearing, handing off, switching tasks, starting a new conversation, or proving that useful chat context has been preserved.',
  '- Pilot Coordinator: load when defining Pilot role, message priority, DecisionBackend choice, executor routing, or matrix-runtime delegation.',
  '- Priority Attention Routing: load when Brief or Pilot must rank competing tasks, blockers, decisions, dependencies, artifacts, or completion chances.',
  '- Native Agent Capability Mapping: load when aligning Codex or Claude Code plan, goal, memory, compact, skills, hooks, subagents, status, or review capabilities to Taskplane product states.',
  '- Source / evidence rules: load when research, citations, source contexts, freshness, credibility, or external facts affect the task.',
  '- Decision Layer Writeback Orchestration: load when runtime evidence must become Write Intent, proposal cards, memory/source/decision updates, or feature impact audit entries.',
  '- Native Agent Runtime Orchestration: load when changing CLI/API runtime architecture, DecisionBackend, persistent goal capability, progress projection, or adapter boundaries.',
  '- Work Habits: retrieve only applicable confirmed habits; do not treat habits as global prompt bulk.',
  '',
  '## Persistence And Write Intent',
  '',
  'Conversation is temporary working context. Persist only when the information changes future recovery, execution, evidence, or user decisions.',
  '',
  'Durable writes must go through Taskplane services and confirmation gates where required. Runtime output can propose Write Intent; it cannot directly mutate Taskplane structured data.',
  '',
  'Use the smallest durable surface:',
  '',
  '- Structured task state for current status, hierarchy, blockers, dependencies, criteria, and next step.',
  '- Task.md for concise recovery.',
  '- Task Records for handoff, closeout, corrections, option rationale, failure review, or source digest.',
  '- Source Context for evidence and research material.',
  '- Decisions for user approval boundaries.',
  '- Artifacts and task files for work products.',
  '',
  '## Context Transition Decision',
  '',
  'Before compacting, resetting, switching tasks, advancing a child, or starting a new conversation, first classify the current chat: temporary noise, active reasoning, recoverable signal, handoff, or decision/blocker.',
  '',
  'GoalPilot owns this trigger decision. If useful signals exist, load Context Transition Policy and require a preservation proof before reset or handoff. If only low-signal repetition exists, keep or continue rather than exposing mode choices. Do not carry task A chat history into task B as if it were task B memory.',
  '',
  '## Verification And Review',
  '',
  'Do not treat generated text, a run result, or an obvious next task as proof that the current task is complete.',
  '',
  'Before closeout, verify against acceptance criteria, user intent, blockers, dependencies, pending decisions, risk, produced files, sources, and evidence.',
  '',
  'Use review/eval after failures, repeated user corrections, risky writes, runtime adapter changes, or task-completion decisions. Feed durable lessons back into the right layer: memory, scoped rule, skill, hook, or test.',
  '',
  '## Anti-Patterns',
  '',
  '- Loading every spec for every turn.',
  '- Asking for secondary preferences instead of drafting a reversible default.',
  '- Executing before goal, boundary, context, or permission is sufficient.',
  '- Treating "need more context" as a reason to ask before trying available self-research, files, memory, or runtime tools.',
  '- Re-decomposing a parent when the user is advancing a child.',
  '- Completing a task because a next task is obvious.',
  '- Treating a runtime-native goal loop as Taskplane\'s source of truth.',
  '- Keeping must-follow rules only in prompt text instead of hooks.',
].join('\n');
