import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

describe('Native Agent Runtime Orchestration spec', () => {
  it('keeps the implementation state aligned with current native CLI writeback support', () => {
    const content = fs.readFileSync(
      path.join(process.cwd(), 'docs/specs/native-agent-runtime-orchestration.md'),
      'utf8',
    );

    expect(content).toContain('pre-run web research bridge');
    expect(content).toContain('research query');
    expect(content).toContain('Right-panel runtime-native goal responses');
    expect(content).toContain('same readiness summary and missing evidence');
    expect(content).toContain('context.readiness.evaluate');
    expect(content).toContain('Pilot coordination is modeled as a product role');
    expect(content).toContain('Phase-2 Pilot assistance is bounded');
    expect(content).toContain('pilot_decision_summary');
    expect(content).toContain('Pilot 决策辅助计划');
    expect(content).toContain('Agent API chat invocations preserve');
    expect(content).toContain('skipped `execution_run`');
    expect(content).toContain('`execution_run` as deferred');
    expect(content).toContain('no provider-visible execution run starts');
    expect(content).toContain('structured promotion');
    expect(content).toContain('Write Intent extraction');
    expect(content).toContain('reviewed-patch apply');
    expect(content).toContain('provider-visible preflight');
    expect(content).toContain('executionRunPromotionRequirements=0/11');
    expect(content).toContain('executionRunMissingRequirements=...');
    expect(content).toContain('executionRunMissingGates=...');
    expect(content).toContain('`product_control_layer` or');
    expect(content).toContain('`persistent_ai_pilot_reserved` is a future');
    expect(content).toContain('future `wanman_matrix` executor');
    expect(content).toContain('completed chat summary');
    expect(content).toContain('local');
    expect(content).toContain('command/workspace activity');
    expect(content).toContain('capability-tagged Run');
    expect(content).toContain('`command_execution` items');
    expect(content).toContain('workspace reads, commands');
    expect(content).toContain('`workspace_write` capability steps are treated as write candidates');
    expect(content).toContain('Terminal Run verification carries same-run artifacts and checkpoints');
    expect(content).toContain('promotion-evidence rule');
    expect(content).toContain('`artifact.propose` Write Intent may carry `kind: "patch"`');
    expect(content).toContain('`imported_patch_artifact` sandbox draft sources');
    expect(content).toContain('explicitly apply an approved reviewed-patch promotion');
    expect(content).toContain('records applied or blocked run evidence');
    expect(content).toContain('no workspace files were');
    expect(content).toContain('Run evidence before re-reviewing');
    expect(content).toContain('post-apply verification results');
    expect(content).toContain('workspace drift blocks apply');
    expect(content).toContain('packaged task-files');
    expect(content).toContain('scheduled, event-triggered, and');
    expect(content).toContain('automaticStartAllowed: false');
    expect(content).toContain('automationReady');
    expect(content).toContain('default read-only');
    expect(content).toContain('scheduledEventEntrypoint=available');
    expect(content).toContain('automatic-start boundary');
    expect(content).toContain('missingRequirements=...');
    expect(content).toContain('runtimeStartMissingRequirements=...');
    expect(content).toContain('AgentStandingApprovalPolicy');
    expect(content).toContain('shared L2 authorization surface');
    expect(content).toContain('standingApprovalReady');
    expect(content).toContain('daily run limit');
    expect(content).toContain('does not create a scheduler');
    expect(content).toContain('buildStandingApprovalConfirmationDraft');
    expect(content).toContain('operator-facing L2');
    expect(content).toContain('schedulerTriggerAllowed=false');
    expect(content).toContain('workspaceWriteAllowed=false');
    expect(content).toContain('blocks other automation readiness gaps');
    expect(content).toContain('panel.standing_approval_confirmed');
    expect(content).toContain('timeline mutation guard');
    expect(content).toContain('separate scheduled/event trigger service');
    expect(content).toContain('planScheduledEventAgentTrigger');
    expect(content).toContain('shared no-start trigger planner');
    expect(content).toContain('confirmed Standing Approval Task Dynamics records');
    expect(content).toContain('explicit daily run-limit accounting input');
    expect(content).toContain('`maxRunsPerDay` is reached');
    expect(content).toContain('dedicated');
    expect(content).toContain('trigger service is explicitly connected');
    expect(content).toContain('trigger Run');
    expect(content).toContain('run-limit count');
    expect(content).toContain('runtimeStartReady');
    expect(content).toContain('SchedulerService.diagnoseScheduledEventAgentTriggers');
    expect(content).toContain('scheduler diagnostic entrypoint');
    expect(content).toContain('RunRepository.countCreatedSinceByTask');
    expect(content).toContain('persisted');
    expect(content).toContain('does not resolve runtime');
    expect(content).toContain('runtimeStartAllowed=false');
    expect(content).toContain('SchedulerService.triggerScheduledEventAgentRun');
    expect(content).toContain('scheduler:triggerScheduledEventAgentRun');
    expect(content).toContain('15-minute');
    expect(content).toContain('dedicated task-source port');
    expect(content).toContain('Code Agent trigger');
    expect(content).toContain('Task Dynamics timeline port');
    expect(content).toContain('before any automatic start can run');
    expect(content).toContain('operatorConfirmed=true');
    expect(content).toContain('automation readiness summary plus satisfied/missing requirements');
    expect(content).toContain('scheduledEventEntrypoint=available');
    expect(content).toContain('lastScheduledEventAgentSweepSummary');
    expect(content).toContain('ports_not_connected');
    expect(content).toContain('in_flight');
    expect(content).toContain('sweep_failed');
    expect(content).toContain('sanitized task-source/trigger-port failure evidence');
    expect(content).toContain('timeline recording fails after a');
    expect(content).toContain('startedRunIds');
    expect(content).toContain('pending_terminal_run_evidence');
    expect(content).toContain('does not count');
    expect(content).toContain('blocked task');
    expect(content).toContain('Failed sweeps');
    expect(content).toContain('release the in-flight');
    expect(content).toContain('in-flight');
    expect(content).toContain('guard');
    expect(content).toContain('background automation');
    expect(content).toContain('health');
    expect(content).toContain('adapter-level native capability declarations');
    expect(content).toContain('provider help output');
    expect(content).toContain('compact/clear context');
    expect(content).toContain('adapter capability support');
    expect(content).toContain('.codex/config.*');
    expect(content).toContain('web/search tool declarations');
    expect(content).toContain('provider-owned CLI `package.json`');
    expect(content).toContain('arbitrary wrappers');
    expect(content).toContain('hook commands or hook entries');
    expect(content).toContain('usable `.claude/agents/*.md` content');
    expect(content).toContain('placeholder-only files do');
    expect(content).toContain('not count as readiness');
    expect(content).toContain('AI Runtime settings surface shows these before a run starts');
    expect(content).toContain('selected-runtime');
    expect(content).toContain('native CLI prompts before execution');
    expect(content).toContain('while the native');
    expect(content).toContain('falls back to parsing the completed stdout transcript');
    expect(content).toContain('task records, task files,');
    expect(content).toContain('artifacts, source contexts, decisions, next-step updates, blockers');
    expect(content).toContain('for task,');
    expect(content).toContain('source, decision, subtask, task-file, and artifact writes');
    expect(content).toContain('Task Dynamics');
    expect(content).toContain('outside the right panel');
    expect(content).toContain('TaskplaneWritebackApprovalItem');
    expect(content).toContain('subtask.propose` is normalized into a `subtask.create_many` apply plan');
    expect(content).toContain('Agent API project-decomposition confirmation path');
    expect(content).toContain('AI 项目拆解自检.md');
    expect(content).toContain('created child task ids and the task record path');
    expect(content).toContain('draft-only before operator confirmation');
    expect(content).not.toContain('completion proposals are not fully wired into the same pipeline');
  });
});
